### PR TITLE
Initial submission from Stanford team.

### PR DESCRIPTION
**Pull request by mcruzloya**
Initial commit including only a negative binomial baseline model. Note that this model differs from CDPH's as a different distribution is fit for every county-month combination and the previous year cases are not used explicitly as a covariate. We plan to submit additional models for subsequent deadlines.

### CODE REVIEW

**Comment by Chipdelmal** [comment]
Hi @mcruzloya ! Thanks for your submission for the WNV challenge!

Was just checking the submission and there's a couple of minor issues.

The first one is that the YML has a strange character in some lines instead of the `"`, I already corrected it in the following snippet, if you want to copy and paste it in yours. I also added the URL for the lab's website as a URL is needed for the submission to validate:

```
team_name: "Mordecai Lab at Stanford University"
team_abbr: "stanford"
model_name: "Negative Binomial Baseline"
model_abbr: "NBB"
model_version: "1.0"
model_contributors: [
  {
    "name": "Mauricio Cruz-Loy",
    "affiliation": "Stanford University",
    "email": "cruzloya@stanford.edu"
  },
  {
    "name": "Joshua Emilio Lazaro",
    "affiliation": "Stanford University",
    "email": "jelazaro@stanford.edu"
  }
]
website_url: "https://www.mordecailab.com/#about-marquee"
license: "CC-BY-4.0"
citation: ""
team_funding: ""
designated_model: true
methods: ""
data_inputs: "WNV case data"
methods_long: "A negative binomial distribution was fit to the case data of all years for each county and month. In cases where the fit was not successful, a Poisson distribution was used instead. For county-month combinations with zero observed cases in all years, a Poisson distribution with a small nonzero mean was used."
ensemble_of_models: false
ensemble_of_hub_models: false
```

The second issue has to do with the CSV file, as some of the values sum to either more or less than 1 due to floating-point rounding. For example:

```
Fresno,2024-04-30,2024-08-31,200,0.9999999999999998,cdf,WNV cases
...
Fresno,2024-04-30,2024-09-30,200,1.0000000000000007,cdf,WNV cases
```

which is throwing warnings on the validation script. It would be best to fix the values to sum up to 1 in the cdf to avoid problems with the hubVerse scheme. 

Thanks for your interest and submission, and we'll be here to help as needed!

**Comment by mcruzloya** [comment]
Apologies for the issues! I think they should be fixed now. Do I need to submit another pull request?

**Comment by Chipdelmal** [comment]
No problem! The same pull request should work but there seem to still be some issues with the CSV file (YML file passed correctly now).

It'd seem that some values are still above 1.0:

Screenshot 2024-04-30 at 9 05 35 PM

and at least some of the CDF distributions are decreasing in value at some points:

Decreasing

**Comment by Chipdelmal** [comment]
In case it is useful, here's a way to check the file locally: https://github.com/cdphmodeling/wnvca-2024/tree/main/model-output#local-validation
For the online validations we have to trigger them until one merge has been successful, after that they are triggered automatically.

**Comment by mcruzloya** [comment]
After some minor modifications, the output csv file seems to pass the tests in my machine.

**Pull request merged**
